=== Tomassone/Universidad/Esercitazioni_PAW/1/addressList-schema.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="nameType">
        <xs:sequence>
            <xs:element name="firstName" type="xs:string"/>
            <xs:element name="secondName" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="surName" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="addressType">
        <xs:sequence>
            <xs:element name="route" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="postalCode" type="xs:string"/>
            <xs:element name="province" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="state" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="informationType">
        <xs:sequence>
            <xs:element name="name" type="nameType"/>
            <xs:element name="address" type="addressType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="telephoneNumber" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="emailAddress" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="nationality" type="xs:string" minOccurs="0" maxOccurs="1"/>
            <xs:element name="note" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="addressListType">
        <xs:sequence>
            <xs:element name="information" type="informationType" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:element name="addressList" type="addressListType"/>
</xs:schema>

=== Tomassone/Universidad/Esercitazioni_PAW/1/addressList.xml
<?xml version="1.0" encoding="utf-8" ?>
<addressList 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="addressList-schema.xsd">
    <name>
        <firstName>Cesare</firstName>
        <surName>Tomasi</surName>
    </name>
    <address>
        <route>Via Arcoveggio 4</route>
        <postalCode>40127</postalCode>
        <province>BO</province>
        <state>Italia</state>
    </address>
    <telephoneNumber>3483401005</telephoneNumber>
    <emailAddress>cec.tomasi@gmail.com</emailAddress>
    <nationality>Italiana</nationality>
    <note>Estremamente figo</note>
</addressList>
