=== Tomassone/Universidad/Esercitazioni_PAW/230623/ES1/resources/InterrogazioniMM.xsd
<?xml version="1.0" ?> 

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:element name="Interrogazioni_MM">
	    <xs:complexType>
	      <xs:sequence>
	      	<xs:element name="Interrogazione_MM" type="interrogazioneMM_Type" maxOccurs="unbounded"/>
	      </xs:sequence>
	    </xs:complexType>
  	</xs:element>
	
	<xs:complexType name="interrogazioneMM_Type"> 
		<xs:sequence> 
			<xs:element name = "ID_input_image" type="xs:string" />
			<xs:element name="modalita">
		        <xs:simpleType>
		        	<xs:restriction base="xs:string">
			            <xs:enumeration value="A"/>
			            <xs:enumeration value="B"/>
			            <xs:enumeration value="C"/>
		          	</xs:restriction>
		        </xs:simpleType>
	        </xs:element>
	        <xs:element name="K" type="xs:positiveInteger"/> 
			<xs:element name = "ID_output_image" type="xs:string" maxOccurs="unbounded"/> <!-- Idealmente maxOccurs = K, ma non permesso da XSD -->
		</xs:sequence> 
  	</xs:complexType> 
	
</xs:schema>

=== Tomassone/Universidad/Esercitazioni_PAW/230623/ES1/resources/InterrogazioniMM.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>

<Interrogazioni_MM  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:noNamespaceSchemaLocation="InterrogazioniMM.xsd">
	
	<Interrogazione_MM>
		<ID_input_image>1000</ID_input_image>
		<modalita>A</modalita>
		<K>5</K>
		<ID_output_image>5001</ID_output_image>
		<ID_output_image>5002</ID_output_image>
		<ID_output_image>5003</ID_output_image>
		<ID_output_image>5004</ID_output_image>
		<ID_output_image>5005</ID_output_image>
	</Interrogazione_MM>
	<Interrogazione_MM>
		<ID_input_image>1001</ID_input_image>
		<modalita>A</modalita>
		<K>5</K>
		<ID_output_image>5011</ID_output_image>
		<ID_output_image>5022</ID_output_image>
		<ID_output_image>5033</ID_output_image>
		<ID_output_image>5044</ID_output_image>
		<ID_output_image>5055</ID_output_image>
	</Interrogazione_MM>
	<Interrogazione_MM>
		<ID_input_image>1002</ID_input_image>
		<modalita>A</modalita>
		<K>5</K>
		<ID_output_image>5101</ID_output_image>
		<ID_output_image>5202</ID_output_image>
		<ID_output_image>5303</ID_output_image>
		<ID_output_image>5404</ID_output_image>
		<ID_output_image>5505</ID_output_image>
	</Interrogazione_MM>    
	
</Interrogazioni_MM>
