=== Tomassone/Universidad/Esercitazioni_PAW/240123/ES1/resources/Visita.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <!-- Tipo email -->
  <xs:simpleType name="emailType">
    <xs:restriction base="xs:string">
      <xs:pattern value="[^@]+@[^@]+\.[^@]+"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Tipo password -->
  <xs:simpleType name="passwordType">
  	<xs:restriction base="xs:string">
    	<xs:length value="8"/>
    	<xs:pattern value="[a-zA-Z0-9?!*$]{8}"/>
  	</xs:restriction>
  </xs:simpleType>

  <!-- Tipo prezzo in euro -->
  <xs:simpleType name="euroType">
    <xs:restriction base="xs:decimal">
      <xs:fractionDigits value="2"/>
      <xs:minInclusive value="0.00"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Tipo capo abbigliamento -->
  <xs:complexType name="itemType">
    <xs:sequence>
      <xs:element name="image" type="xs:string"/>
      <xs:element name="description" type="xs:string"/>
      <xs:element name="price" type="euroType"/>
      <xs:element name="selected" type="xs:boolean" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Tipo per ogni scelta (es. abiti, gonne, ecc.) -->
  <xs:complexType name="choiceType">
    <xs:sequence>
      <xs:element name="item" type="itemType" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

  <!-- Tipo principale -->
  <xs:complexType name="visitaType">
    <xs:sequence>
      <xs:element name="email" type="emailType"/>
      <xs:element name="password" type="passwordType"/>
      
      <!-- Almeno una categoria richiesta -->
      <xs:element name="scelte" minOccurs="1">
      <xs:complexType>
        <xs:choice minOccurs="1" maxOccurs="unbounded">
          <xs:element name="abiti" type="choiceType"/>
          <xs:element name="camice" type="choiceType"/>
          <xs:element name="giacche" type="choiceType"/>
          <xs:element name="gonne" type="choiceType"/>
          <xs:element name="pantaloni" type="choiceType"/>
          <xs:element name="ultimi_arrivi" type="choiceType"/>
        </xs:choice>
      </xs:complexType>
    </xs:element>
   </xs:sequence>
  </xs:complexType>

  <!-- Elemento radice -->
  <xs:element name="visita" type="visitaType"/>

</xs:schema>

=== Tomassone/Universidad/Esercitazioni_PAW/240123/ES1/resources/Visita.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>

<!-- decommentare qui sotto per validare tramite DTD -->
<!--
<!DOCTYPE Address_list SYSTEM "AddressList.dtd">  
<Address_list>
-->

<!-- decommentare qui sotto  per validare tramite XSD  -->
<!-- -->
<visita  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
         xsi:noNamespaceSchemaLocation="Visita.xsd">
	<email>farinelli.diletta@gmail.com</email>
	<password>abcdefgh</password>
	<scelte>
		<abiti>
			<item>
				<image>foto.jpg</image>
			
				<description>vestito sbarazzino</description>
			
				<price>23</price>
			
				<selected>true</selected>
			</item>
		</abiti>
		<pantaloni>
			<item>
				<image>foto1.jpg</image>
			
				<description>jeans sbarazzini</description>
			
				<price>26</price>
			
			</item>
		</pantaloni> 
	</scelte>
</visita>
